version: "3"

services:
  mysql:
    image: mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root
    container_name: taskManagerDatabase
